name: test for ${{ inputs.project_name }}
author: nawaphon
description: run unit tests for ${{ inputs.project_name }}
inputs:
  project_name:
    description: 'Project name to test'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.6'

    - name: Test
      run: go test -v ${{ format('./{0}/', inputs.project_name) }}
      shell: bash