name: test for ${{ inputs.project_name }}
author: nawaphon
description: run unit tests for ${{ inputs.project_name }}
inputs:
  project_name:
    description: 'Project name to test'
    required: true

runs:
  using: "composite"
  steps:

    - name: Test
      run: go test -v ${{ format('./{0}/', inputs.project_name) }}
      shell: bash