name: test_steps_template
author: nawaphon
description: run unit tests for each project name
inputs:
  project_name:
    description: 'Project name to test'
    required: true

runs:
  using: "composite"
  steps:

    - name: Test ${{ inputs.project_name }}
      run: go test -v ${{ format('./{0}/', inputs.project_name) }}
      shell: bash