name: test everynight
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        project_name: [ 'kv_server_lock_mechanism', 'kv_server_lock_mechanism_unstable_network', 'kv_server_with_drop_message', 'kv_server_with_stable_network' ]
    uses: ./.github/workflows/test_workflow.yml
    with:
      project_name: ${{ matrix.project_name }}
