name: test everynight
run-name: test everynight for ${{ inputs.project_name }}
on:
  workflow_call:
    inputs:
      project_name:
        description: 'project name to test'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.6'

      - uses: ./.github/actions/test_steps_template
        with:
          project_name: ${{ inputs.project_name }}
